colnames(iris)
levels(iris$Species)
library(rpart)
library(rpart.plot)
train <- sample(1:150,100)
tree<-rpart(Species~Sepal.Length+Sepal.Width+Petal.Length+Petal.Width, data = iris, subset= train, method = "class")
rpart.plot(tree)
summary(tree)
printcp(tree)
pruned_tree<- prune(tree,cp=0.1)
predict(pruned_tree, iris[-train,], type = "class")
(tt<-table(iris$Species[-train],predict(pruned_tree,iris[-train,],type = "class")))
sum(tt[row(tt) == col(tt)])/sum(tt)
1-sum(tt[row(tt) == col(tt)])/sum(tt)
test <- iris[-train,]
test$pred<-predict(pruned_tree, iris[-train,],type = "class")
library(ggplot2)
ggplot(test, aes(Species, pred, color = Species))+geom_jitter(width = 0.2,height = 0.1,size =2)+labs(title = "Confusion Matrix",subtitle = "Predicted vs. Observed from Iris dataset", y = "Predicted",x="Truth")
